em28xx-y +=	em28xx-video.o em28xx-i2c.o em28xx-cards.o
em28xx-y +=	em28xx-core.o  em28xx-vbi.o em28xx-camera.o

em28xx-alsa-objs := em28xx-audio.o
#em28xx-rc-objs := em28xx-input.o

obj-m += em28xx-alsa.o
obj-m += em28xx.o
#obj-m += em28xx-dvb.o
#obj-m += em28xx-rc.o
